[package]
name = "duplicate-file-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
notify-rust = { version = "4.11.6", features = [] }
notify = { version = "8.0.0", features = [] }
notify-debouncer-mini = { version = "0.6.0", features = [] }